### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by tehfink** [criecm/ansible-role-iocage#1]
Hi! Thanks for writing this role. Do you expect it to support Python 3 soon?

**Comment by dgeo** [comment]
did you test this ?
I think it could work without big changes, but no time for this now as ansible is still on python2 primarily.

Once ansible needs python >= 3.6, the module could use iocage's library directly with slightly more changes instead of using command-line…

**Comment by dgeo** [comment]
just tested with embedded tests: it seems to work out of the box :)
Feel free to test further ans re-open this if needed
