### ISSUE TITLE
OSX Source /root/.ssh/authorized_keys not found 

### ISSUE THREAD

**Issue by mike-pt** [criecm/ansible-role-iocage#3]
This seems to be hard-coded in the tasks and so fails if the file doesn't exits 

`fatal: [fbsdtest]: FAILED! => {"changed": false, "msg": "Source /root/.ssh/authorized_keys not found"}`

On macos by default `/root` isn't even there.

Also it would be useful if we could skip the task to enable sshd on the jail (I mostly prefer to use jexec and not enable ssh for say a mysql server jail ) now for others it might still be useful ofc, say enable sshd and allow sftp access to files etc

**Comment by dgeo** [comment]
This makes sense, I think i'll make this configurable ASAP

**Comment by mike-pt** [comment]
I think for the "don't enable sshd part" it would work if I set the jails as "templates" after in the end its just a flag, but it seems in you're code this task are only done for none template jails.

**Comment by dgeo** [comment]
Now you can just set 'iocage_enable_ssh' to False :)
Tell me how it goes ;)
